edition = "2018"
max_width = 100
tab_spaces = 4
control_brace_style = "ClosingNextLine"
empty_item_single_line = false
enum_discrim_align_threshold = 50
indent_style = "Block"
match_block_trailing_comma = true
overflow_delimited_expr = true
reorder_impl_items = true
use_field_init_shorthand = true

