[package]
name = "testapp"
version = "0.1.0"
authors = ["Nils Asmussen <nils@os.inf.tu-dresden.de>"]
edition = "2018"

[lib]
name = "testapp"
crate-type = ["staticlib"]

[dependencies]
rlibc = "1.0.0"
