[package]
name = "words"
version = "0.1.0"
authors = ["Nils Asmussen <nils@os.inf.tu-dresden.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
